[package]
name = "tower-sessions-sqlx-store-chrono"
description = "SQLx session stores for `tower-sessions` but using `chrono` instead of `time`."
version = "0.14.2"
edition = "2021"
authors = [
    "Karuna Murti <karuna.murti@gmail.com>",
    "Max Countryman <hello@maxcountryman.com>",
]
license = "MIT"
homepage = "https://github.com/karuna/tower-sessions-sqlx-store-chrono"
keywords = ["axum", "sessions", "cookie", "tower", "sqlx"]
categories = ["asynchronous", "network-programming", "web-programming"]
repository = "https://github.com/karuna/tower-sessions-sqlx-store-chrono"
documentation = "https://docs.rs/tower-sessions-sqlx-store-chrono"
readme = "README.md"

[features]
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]

[dependencies]
axum = "0.8.1"
async-trait = "0.1.85"
chrono = "0.4"
rmp-serde = "1.1.2"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "chrono"] }
thiserror = "2.0.11"
time = "0.3"
tower-sessions-core = { version = "0.14", features = ["deletion-task"] }

[dev-dependencies]
tower-sessions = "0.14"
tokio = { version = "1.43.0", features = ["full"] }
tokio-test = "0.4.3"
serde = "1"

[[example]]
name = "sqlite"
required-features = ["sqlite"]

[[example]]
name = "postgres"
required-features = ["postgres"]

[[example]]
name = "mysql"
required-features = ["mysql"]
